/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  ValidateNested,
  IsOptional,
  IsNumber,
  IsString,
} from "class-validator";
import { Type } from "class-transformer";
import { DeliveryAreaGroup } from "../../deliveryAreaGroup/base/DeliveryAreaGroup";
import { DeliverySlot } from "../../deliverySlot/base/DeliverySlot";
import { ServicePoint } from "../../servicePoint/base/ServicePoint";
@ObjectType()
class DeliveryArea {
  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: () => DeliveryAreaGroup,
  })
  @ValidateNested()
  @Type(() => DeliveryAreaGroup)
  @IsOptional()
  deliveryAreaGroup?: DeliveryAreaGroup | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  deliveryPrice!: number | null;

  @ApiProperty({
    required: false,
    type: () => [DeliverySlot],
  })
  @ValidateNested()
  @Type(() => DeliverySlot)
  @IsOptional()
  deliverySlots?: Array<DeliverySlot>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description!: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  geoLocation!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: () => ServicePoint,
  })
  @ValidateNested()
  @Type(() => ServicePoint)
  @IsOptional()
  servicePoint?: ServicePoint | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  tenantId!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}
export { DeliveryArea };
