/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DeliveryAreaGroupWhereUniqueInput } from "../../deliveryAreaGroup/base/DeliveryAreaGroupWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { DeliverySlotListRelationFilter } from "../../deliverySlot/base/DeliverySlotListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { ServicePointWhereUniqueInput } from "../../servicePoint/base/ServicePointWhereUniqueInput";
import { StringNullableFilter } from "../../util/StringNullableFilter";
@InputType()
class DeliveryAreaWhereInput {
  @ApiProperty({
    required: false,
    type: () => DeliveryAreaGroupWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DeliveryAreaGroupWhereUniqueInput)
  @IsOptional()
  @Field(() => DeliveryAreaGroupWhereUniqueInput, {
    nullable: true,
  })
  deliveryAreaGroup?: DeliveryAreaGroupWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => DeliverySlotListRelationFilter,
  })
  @ValidateNested()
  @Type(() => DeliverySlotListRelationFilter)
  @IsOptional()
  @Field(() => DeliverySlotListRelationFilter, {
    nullable: true,
  })
  deliverySlots?: DeliverySlotListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  geoLocation?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  name?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => ServicePointWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ServicePointWhereUniqueInput)
  @IsOptional()
  @Field(() => ServicePointWhereUniqueInput, {
    nullable: true,
  })
  servicePoint?: ServicePointWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  tenantId?: StringNullableFilter;
}
export { DeliveryAreaWhereInput };
