/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DeliveryAreaGroupService } from "../deliveryAreaGroup.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeliveryAreaGroupCreateInput } from "./DeliveryAreaGroupCreateInput";
import { DeliveryAreaGroupWhereInput } from "./DeliveryAreaGroupWhereInput";
import { DeliveryAreaGroupWhereUniqueInput } from "./DeliveryAreaGroupWhereUniqueInput";
import { DeliveryAreaGroupFindManyArgs } from "./DeliveryAreaGroupFindManyArgs";
import { DeliveryAreaGroupUpdateInput } from "./DeliveryAreaGroupUpdateInput";
import { DeliveryAreaGroup } from "./DeliveryAreaGroup";
import { DeliveryAreaFindManyArgs } from "../../deliveryArea/base/DeliveryAreaFindManyArgs";
import { DeliveryArea } from "../../deliveryArea/base/DeliveryArea";
import { DeliveryAreaWhereUniqueInput } from "../../deliveryArea/base/DeliveryAreaWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DeliveryAreaGroupControllerBase {
  constructor(
    protected readonly service: DeliveryAreaGroupService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "DeliveryAreaGroup",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DeliveryAreaGroup })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: DeliveryAreaGroupCreateInput
  ): Promise<DeliveryAreaGroup> {
    return await this.service.create({
      data: {
        ...data,

        servicePoint: data.servicePoint
          ? {
              connect: data.servicePoint,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        name: true,

        servicePoint: {
          select: {
            id: true,
          },
        },

        tenantId: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "DeliveryAreaGroup",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [DeliveryAreaGroup] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(DeliveryAreaGroupFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<DeliveryAreaGroup[]> {
    const args = plainToClass(DeliveryAreaGroupFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,

        servicePoint: {
          select: {
            id: true,
          },
        },

        tenantId: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "DeliveryAreaGroup",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DeliveryAreaGroup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: DeliveryAreaGroupWhereUniqueInput
  ): Promise<DeliveryAreaGroup | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,

        servicePoint: {
          select: {
            id: true,
          },
        },

        tenantId: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "DeliveryAreaGroup",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DeliveryAreaGroup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: DeliveryAreaGroupWhereUniqueInput,
    @common.Body() data: DeliveryAreaGroupUpdateInput
  ): Promise<DeliveryAreaGroup | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          servicePoint: data.servicePoint
            ? {
                connect: data.servicePoint,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          name: true,

          servicePoint: {
            select: {
              id: true,
            },
          },

          tenantId: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "DeliveryAreaGroup",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DeliveryAreaGroup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: DeliveryAreaGroupWhereUniqueInput
  ): Promise<DeliveryAreaGroup | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,

          servicePoint: {
            select: {
              id: true,
            },
          },

          tenantId: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "DeliveryArea",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/deliveryAreas")
  @ApiNestedQuery(DeliveryAreaFindManyArgs)
  async findManyDeliveryAreas(
    @common.Req() request: Request,
    @common.Param() params: DeliveryAreaGroupWhereUniqueInput
  ): Promise<DeliveryArea[]> {
    const query = plainToClass(DeliveryAreaFindManyArgs, request.query);
    const results = await this.service.findDeliveryAreas(params.id, {
      ...query,
      select: {
        createdAt: true,

        deliveryAreaGroup: {
          select: {
            id: true,
          },
        },

        deliveryPrice: true,
        description: true,
        geoLocation: true,
        id: true,
        name: true,

        servicePoint: {
          select: {
            id: true,
          },
        },

        tenantId: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "DeliveryAreaGroup",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/deliveryAreas")
  async connectDeliveryAreas(
    @common.Param() params: DeliveryAreaGroupWhereUniqueInput,
    @common.Body() body: DeliveryAreaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      deliveryAreas: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "DeliveryAreaGroup",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/deliveryAreas")
  async updateDeliveryAreas(
    @common.Param() params: DeliveryAreaGroupWhereUniqueInput,
    @common.Body() body: DeliveryAreaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      deliveryAreas: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "DeliveryAreaGroup",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/deliveryAreas")
  async disconnectDeliveryAreas(
    @common.Param() params: DeliveryAreaGroupWhereUniqueInput,
    @common.Body() body: DeliveryAreaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      deliveryAreas: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
