/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  ValidateNested,
  IsBoolean,
} from "class-validator";
import { DeliveryAreaGroupUpdateManyWithoutServicePointsInput } from "./DeliveryAreaGroupUpdateManyWithoutServicePointsInput";
import { Type } from "class-transformer";
import { DeliveryAreaUpdateManyWithoutServicePointsInput } from "./DeliveryAreaUpdateManyWithoutServicePointsInput";
import { DeliverySlotUpdateManyWithoutServicePointsInput } from "./DeliverySlotUpdateManyWithoutServicePointsInput";
import { PickupLocationUpdateManyWithoutServicePointsInput } from "./PickupLocationUpdateManyWithoutServicePointsInput";
import { PickupSlotUpdateManyWithoutServicePointsInput } from "./PickupSlotUpdateManyWithoutServicePointsInput";
import { ProductUpdateManyWithoutServicePointsInput } from "./ProductUpdateManyWithoutServicePointsInput";
import { TenantWhereUniqueInput } from "../../tenant/base/TenantWhereUniqueInput";
@InputType()
class ServicePointUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string;

  @ApiProperty({
    required: false,
    type: () => DeliveryAreaGroupUpdateManyWithoutServicePointsInput,
  })
  @ValidateNested()
  @Type(() => DeliveryAreaGroupUpdateManyWithoutServicePointsInput)
  @IsOptional()
  @Field(() => DeliveryAreaGroupUpdateManyWithoutServicePointsInput, {
    nullable: true,
  })
  deliveryAreaGroups?: DeliveryAreaGroupUpdateManyWithoutServicePointsInput;

  @ApiProperty({
    required: false,
    type: () => DeliveryAreaUpdateManyWithoutServicePointsInput,
  })
  @ValidateNested()
  @Type(() => DeliveryAreaUpdateManyWithoutServicePointsInput)
  @IsOptional()
  @Field(() => DeliveryAreaUpdateManyWithoutServicePointsInput, {
    nullable: true,
  })
  deliveryAreas?: DeliveryAreaUpdateManyWithoutServicePointsInput;

  @ApiProperty({
    required: false,
    type: () => DeliverySlotUpdateManyWithoutServicePointsInput,
  })
  @ValidateNested()
  @Type(() => DeliverySlotUpdateManyWithoutServicePointsInput)
  @IsOptional()
  @Field(() => DeliverySlotUpdateManyWithoutServicePointsInput, {
    nullable: true,
  })
  deliverySlots?: DeliverySlotUpdateManyWithoutServicePointsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  ghanaPostGps?: string;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isActive?: boolean;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string;

  @ApiProperty({
    required: false,
    type: () => PickupLocationUpdateManyWithoutServicePointsInput,
  })
  @ValidateNested()
  @Type(() => PickupLocationUpdateManyWithoutServicePointsInput)
  @IsOptional()
  @Field(() => PickupLocationUpdateManyWithoutServicePointsInput, {
    nullable: true,
  })
  pickupLocations?: PickupLocationUpdateManyWithoutServicePointsInput;

  @ApiProperty({
    required: false,
    type: () => PickupSlotUpdateManyWithoutServicePointsInput,
  })
  @ValidateNested()
  @Type(() => PickupSlotUpdateManyWithoutServicePointsInput)
  @IsOptional()
  @Field(() => PickupSlotUpdateManyWithoutServicePointsInput, {
    nullable: true,
  })
  pickupSlots?: PickupSlotUpdateManyWithoutServicePointsInput;

  @ApiProperty({
    required: false,
    type: () => ProductUpdateManyWithoutServicePointsInput,
  })
  @ValidateNested()
  @Type(() => ProductUpdateManyWithoutServicePointsInput)
  @IsOptional()
  @Field(() => ProductUpdateManyWithoutServicePointsInput, {
    nullable: true,
  })
  products?: ProductUpdateManyWithoutServicePointsInput;

  @ApiProperty({
    required: false,
    type: () => TenantWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TenantWhereUniqueInput)
  @IsOptional()
  @Field(() => TenantWhereUniqueInput, {
    nullable: true,
  })
  tenant?: TenantWhereUniqueInput;
}
export { ServicePointUpdateInput };
