/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  ValidateNested,
  IsOptional,
  IsBoolean,
} from "class-validator";
import { DeliveryAreaGroupCreateNestedManyWithoutServicePointsInput } from "./DeliveryAreaGroupCreateNestedManyWithoutServicePointsInput";
import { Type } from "class-transformer";
import { DeliveryAreaCreateNestedManyWithoutServicePointsInput } from "./DeliveryAreaCreateNestedManyWithoutServicePointsInput";
import { DeliverySlotCreateNestedManyWithoutServicePointsInput } from "./DeliverySlotCreateNestedManyWithoutServicePointsInput";
import { PickupLocationCreateNestedManyWithoutServicePointsInput } from "./PickupLocationCreateNestedManyWithoutServicePointsInput";
import { PickupSlotCreateNestedManyWithoutServicePointsInput } from "./PickupSlotCreateNestedManyWithoutServicePointsInput";
import { ProductCreateNestedManyWithoutServicePointsInput } from "./ProductCreateNestedManyWithoutServicePointsInput";
import { TenantWhereUniqueInput } from "../../tenant/base/TenantWhereUniqueInput";
@InputType()
class ServicePointCreateInput {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  address!: string;

  @ApiProperty({
    required: false,
    type: () => DeliveryAreaGroupCreateNestedManyWithoutServicePointsInput,
  })
  @ValidateNested()
  @Type(() => DeliveryAreaGroupCreateNestedManyWithoutServicePointsInput)
  @IsOptional()
  @Field(() => DeliveryAreaGroupCreateNestedManyWithoutServicePointsInput, {
    nullable: true,
  })
  deliveryAreaGroups?: DeliveryAreaGroupCreateNestedManyWithoutServicePointsInput;

  @ApiProperty({
    required: false,
    type: () => DeliveryAreaCreateNestedManyWithoutServicePointsInput,
  })
  @ValidateNested()
  @Type(() => DeliveryAreaCreateNestedManyWithoutServicePointsInput)
  @IsOptional()
  @Field(() => DeliveryAreaCreateNestedManyWithoutServicePointsInput, {
    nullable: true,
  })
  deliveryAreas?: DeliveryAreaCreateNestedManyWithoutServicePointsInput;

  @ApiProperty({
    required: false,
    type: () => DeliverySlotCreateNestedManyWithoutServicePointsInput,
  })
  @ValidateNested()
  @Type(() => DeliverySlotCreateNestedManyWithoutServicePointsInput)
  @IsOptional()
  @Field(() => DeliverySlotCreateNestedManyWithoutServicePointsInput, {
    nullable: true,
  })
  deliverySlots?: DeliverySlotCreateNestedManyWithoutServicePointsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  email!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  ghanaPostGps!: string;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isActive!: boolean;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  phone!: string;

  @ApiProperty({
    required: false,
    type: () => PickupLocationCreateNestedManyWithoutServicePointsInput,
  })
  @ValidateNested()
  @Type(() => PickupLocationCreateNestedManyWithoutServicePointsInput)
  @IsOptional()
  @Field(() => PickupLocationCreateNestedManyWithoutServicePointsInput, {
    nullable: true,
  })
  pickupLocations?: PickupLocationCreateNestedManyWithoutServicePointsInput;

  @ApiProperty({
    required: false,
    type: () => PickupSlotCreateNestedManyWithoutServicePointsInput,
  })
  @ValidateNested()
  @Type(() => PickupSlotCreateNestedManyWithoutServicePointsInput)
  @IsOptional()
  @Field(() => PickupSlotCreateNestedManyWithoutServicePointsInput, {
    nullable: true,
  })
  pickupSlots?: PickupSlotCreateNestedManyWithoutServicePointsInput;

  @ApiProperty({
    required: false,
    type: () => ProductCreateNestedManyWithoutServicePointsInput,
  })
  @ValidateNested()
  @Type(() => ProductCreateNestedManyWithoutServicePointsInput)
  @IsOptional()
  @Field(() => ProductCreateNestedManyWithoutServicePointsInput, {
    nullable: true,
  })
  products?: ProductCreateNestedManyWithoutServicePointsInput;

  @ApiProperty({
    required: true,
    type: () => TenantWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TenantWhereUniqueInput)
  @Field(() => TenantWhereUniqueInput)
  tenant!: TenantWhereUniqueInput;
}
export { ServicePointCreateInput };
