/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsInt,
  IsOptional,
  IsDate,
  IsString,
  IsNumber,
  IsBoolean,
  ValidateNested,
  IsEnum,
} from "class-validator";

import { Type } from "class-transformer";
import { PickupLocationWhereUniqueInput } from "../../pickupLocation/base/PickupLocationWhereUniqueInput";
import { ServicePointWhereUniqueInput } from "../../servicePoint/base/ServicePointWhereUniqueInput";
import { EnumPickupSlotSlotType } from "./EnumPickupSlotSlotType";
@InputType()
class PickupSlotUpdateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  cutOffTime?: number | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  date?: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  day?: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  deliveryPrice?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  endTime?: string;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isActive?: boolean;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isBooked?: boolean;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  orderQuota?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  pickingPrice?: number | null;

  @ApiProperty({
    required: false,
    type: () => PickupLocationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PickupLocationWhereUniqueInput)
  @IsOptional()
  @Field(() => PickupLocationWhereUniqueInput, {
    nullable: true,
  })
  pickupLocation?: PickupLocationWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ServicePointWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ServicePointWhereUniqueInput)
  @IsOptional()
  @Field(() => ServicePointWhereUniqueInput, {
    nullable: true,
  })
  servicePoint?: ServicePointWhereUniqueInput;

  @ApiProperty({
    required: false,
    enum: EnumPickupSlotSlotType,
  })
  @IsEnum(EnumPickupSlotSlotType)
  @IsOptional()
  @Field(() => EnumPickupSlotSlotType, {
    nullable: true,
  })
  slotType?: "RE_CURRENT" | "ABSOLUTE" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  startTime?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  tenantId?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  validFrom?: Date;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  validTo?: Date;
}
export { PickupSlotUpdateInput };
