/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsInt,
  IsOptional,
  IsDate,
  IsString,
  IsNumber,
  IsBoolean,
  ValidateNested,
  IsEnum,
} from "class-validator";

import { Type } from "class-transformer";
import { PickupLocationWhereUniqueInput } from "../../pickupLocation/base/PickupLocationWhereUniqueInput";
import { ServicePointWhereUniqueInput } from "../../servicePoint/base/ServicePointWhereUniqueInput";
import { EnumPickupSlotSlotType } from "./EnumPickupSlotSlotType";
@InputType()
class PickupSlotCreateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  cutOffTime?: number | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  date!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  day!: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  deliveryPrice?: number | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  endTime!: string;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isActive!: boolean;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isBooked!: boolean;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  orderQuota?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  pickingPrice?: number | null;

  @ApiProperty({
    required: false,
    type: () => PickupLocationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PickupLocationWhereUniqueInput)
  @IsOptional()
  @Field(() => PickupLocationWhereUniqueInput, {
    nullable: true,
  })
  pickupLocation?: PickupLocationWhereUniqueInput | null;

  @ApiProperty({
    required: true,
    type: () => ServicePointWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ServicePointWhereUniqueInput)
  @Field(() => ServicePointWhereUniqueInput)
  servicePoint!: ServicePointWhereUniqueInput;

  @ApiProperty({
    required: false,
    enum: EnumPickupSlotSlotType,
  })
  @IsEnum(EnumPickupSlotSlotType)
  @IsOptional()
  @Field(() => EnumPickupSlotSlotType, {
    nullable: true,
  })
  slotType?: "RE_CURRENT" | "ABSOLUTE" | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  startTime!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  tenantId?: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  validFrom!: Date;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  validTo!: Date;
}
export { PickupSlotCreateInput };
