/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsNumber,
  IsString,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { PickupSlotCreateNestedManyWithoutPickupLocationsInput } from "./PickupSlotCreateNestedManyWithoutPickupLocationsInput";
import { Type } from "class-transformer";
import { ServicePointWhereUniqueInput } from "../../servicePoint/base/ServicePointWhereUniqueInput";
@InputType()
class PickupLocationCreateInput {
  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Field(() => Number)
  deliveryPrice!: number;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  geoLocation!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: () => PickupSlotCreateNestedManyWithoutPickupLocationsInput,
  })
  @ValidateNested()
  @Type(() => PickupSlotCreateNestedManyWithoutPickupLocationsInput)
  @IsOptional()
  @Field(() => PickupSlotCreateNestedManyWithoutPickupLocationsInput, {
    nullable: true,
  })
  pickupSlots?: PickupSlotCreateNestedManyWithoutPickupLocationsInput;

  @ApiProperty({
    required: true,
    type: () => ServicePointWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ServicePointWhereUniqueInput)
  @Field(() => ServicePointWhereUniqueInput)
  servicePoint!: ServicePointWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  tenantId?: string | null;
}
export { PickupLocationCreateInput };
